### ISSUE TITLE
Daniel Somoza Frontend onboarding

### ISSUE THREAD

**Issue by DaniSomoza** [gnosis/onboarding-docs#5]
# Gnosis Frontend Onboarding

## Safe App

Write a simple [Safe app](https://docs.gnosis.io/safe/docs/sdks_safe_apps/) using the knowledge from the general onboarding.
Ask the team what idea would make sense to work on. Feel free to suggest your own ideas.

- [ ] Make a pull request to https://github.com/gnosis/safe-react-apps, paste the link in comments
- [ ] Assign 2 reviewers from the team

## Safe React

Safe React is our main repository where most of the work is happening.

Your next task will be to work on a small bugfix. Ask the team for help.

- [x] Read the project [readme](https://github.com/gnosis/safe-react#readme)
- [x] Configure your local environment and run the app
- [x] Run the unit tests
- [x] Make a pull request to https://github.com/gnosis/safe-react, paste the link in comments

## Safe React Components

This is our component library. It's used by both Safe Apps and by the Safe itself.

- [x] Check out the [component library](https://components.gnosis-safe.io)
- [x] Read the [readme](https://github.com/gnosis/safe-react-components#readme) and run the storybook locally
- [x] Make a pull request to https://github.com/gnosis/safe-react-components

**Comment by katspaugh** [comment]
@DaniSomoza I suggest we close this. Making an app is optional, and you work on the Safe Apps team anyway 😄
